spring.application.name=lame-book-store-app

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/book-store-db
spring.datasource.username=postgres
spring.datasource.password=nuster
spring.jpa.open-in-view=false

jwt.expiration=30000
jwt.secret=2VOYH4HYVZQIRYWDXTCWJSF21ZSSJERI
